# Read the Docs configuration file
# More info on https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: '3.8'

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs