[tool.poetry]
name = "mwr_raw2l1"
version = "0.1.3"
description = ""  # TODO: add description
authors = ["rruefenacht <rruefenacht@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.6.8,<3.11"  # for scipy
netCDF4 = [
    {version = "^1.5.8", python = "3.6"},
    {version = "^1.5.8", python = ">=3.7"}
    ]
PyYAML = "^6"
numpy = [
    {version = "=1.21", python = "3.6"},
    {version = "^1.21", python = ">=3.7"}
    ]
scipy = [  # needed for xarray.Dataset.interp
    {version = "=1.5.4", python = "3.6"},
    {version = '^1.7.3', python = ">=3.7"}
    ]
xarray = [
    {version = "=0.16.2", python = "3.6"},
    {version = "^0.20.2", python = ">=3.7"}
    ]
ephem = "^4.1"  # used for setting sun-in-beam flag in quality_flag
colorlog = {version = "^6.6", optional = true}


[tool.poetry.dev-dependencies]
flake8 = [
        {version = "=1.21", python = "3.6"},
        {version = "^3.9", python = ">=3.7"}
	 ]
flake8-blind-except = "^0.2"
flake8-coding = "^1.3"
flake8-commas = "^2.1"
flake8-debugger = [
        {version = "=3.2.1", python = "3.6"},
        {version = "^4.1", python = ">=3.7"}
	    ]
flake8-deprecated = "^1.3"
flake8-isort = "^4.0"
flake8-pep3101 = "^1.3"
flake8-print = [
        {version = "=3.1.4", python = "3.6"},
        {version = "^5.0", python = ">=3.7"}
	 ]
flake8-quotes = "^3.3"
flake8-string-format = "^0.3"
flake8-todo = "^0.7"

isort = "^5.10"

matplotlib = [
        {version = "=3.3", python = "3.6"},
        {version = "^3.5", python = ">=3.7"}
	    ]

Sphinx = [
        {version = "=4.3.2", python = "3.6"},
        {version = "^4.5", python = ">=3.7"}
	    ]
sphinxcontrib-napoleon = "^0.7"
sphinx-rtd-theme = "^1.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mwr_raw2l1 = "mwr_raw2l1.__main__:main"

[tool.poetry.extras]
colorlog = ["colorlog"]

[tool.isort]
line_length = 120
