[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mwr_raw2l1"
version = "0.1.3"
description = "This project provides readers for the data files of the the most prominent types of operational ground-based K- and V-band microwave radiometers and a writer for NetCDF files according to E-PROFILE/ACTRIS standards."
authors = [ "Rolf Rüfenacht (MeteoSwiss, rruefenacht <rruefenacht@users.noreply.github.com>)",]

[tool.isort]
line_length = 120

[tool.poetry.dependencies]
python = "3.6.8"
netCDF4 = "1.5.8"
PyYAML = "6.0"
numpy = "1.21"
scipy = "0.16.2"
xarray = "0.16.2"
ephem = "4.1"

[tool.poetry.dev-dependencies]
matplotlib = "3.3"
flake8 = "1.21"
isort = "5.10"
Sphinx = "4.3.2"
sphinx-rtd-theme = "1.0"
sphinxcontrib-napoleon = "0.7"
toml = "0.10.2"

[tool.poetry.scripts]
mwr_raw2l1 = "mwr_raw2l1.__main__:main"

[tool.poetry.extras]
colorlog = [ "colorlog",]

[tool.poetry.dependencies.colorlog]
version = "6.6"
optional = true
