# python version
python = "3.6.8"

# core dependencies
netCDF4 = "1.5.8"
PyYAML = "6.0"
numpy = "1.21"
scipy = "0.16.2"
xarray = "0.16.2"
ephem = "4.1"

# extra dependencies
colorlog = "6.6"

# development dependencies
flake8 = "1.21"
isort = "5.10"
matplotlib = "3.3"
Sphinx = "4.3.2"
toml = "0.10.2"
flake8-blind-except = "0.2"
flake8-coding = "1.3"
flake8-commas = "2.1"
flake8-debugger = "3.2.1"
flake8-deprecated = "1.3"
flake8-isort = "4.0"
flake8-pep3101 = "1.3"
flake8-print = "3.1.4"
flake8-quotes = "3.3"
flake8-string-format = "0.3"
flake8-todo = "0.7"
sphinxcontrib-napoleon = "0.7"
sphinx-rtd-theme = "1.0"
