# config file example for a Attex MTP5-HE in Padua, Italy

reader: reader_attex   # refers to name set at import into main.py near line 10
meas_constructor: from_attex  # constructor for Measurement class in measurement.measurement.py

input_directory: data/attex/0-20000-0-99999/  # use absolute path (or relative to location of main.py)
output_directory: data/output/  # use absolute path (or relative to location of main.py)
base_filename_in: MWR_0-20000-0-99999_A
base_filename_out: MWR_1C01_0-20000-0-99999_A

station_latitude: 45.40
station_longitude: 11.88
station_altitude: 30

ir_wavelength: .NaN  # need to specify as NaN if no IR instrument present

nc_attributes:
  # title: do not set 'title' attribute unless you have a very good reason to deviate from the default
  wigos_station_id: 0-20000-0-99999
  instrument_id: A
  site_location: Padua, Italy
  institution: ARPA Veneto
  principal_investigator: Remote Sensing Group
  instrument_manufacturer: ATTEX
  instrument_model: MTP5
  instrument_generation: HE
  instrument_hw_id: to_be_specified
  instrument_history: to_be_specified
  ir_instrument_manufacturer: No IR instrument
  ir_instrument_model: No IR instrument
  ir_instrument_fabrication_year: No IR instrument
  met_instrument_manufacturer: to_be_specified
  met_instrument_model: to_be_specified
  met_instrument_fabrication_year: to_be_specified
  # the following attributes are potentially varying with time:
  instrument_calibration_status: calibrated
  date_of_last_absolute_calibration: '2021-12-31 23:59:59'  # dates for global attrs need to be specified as str
  date_of_last_covariance_matrix: '2021-12-31 23:59:59'  # dates for global attrs need to be specified as str
  type_of_automatic_calibrations: opaque atmosphere at low elevation and internal load


# additional optional fields for nc_attributes
  # network: E-PROFILE, ...
  # campaign_name: ...
  # comment: ...
  # license: ...
  # air_temperature_accuracy: ...
  # relative_humidity_accuracy: ...
  # air_pressure_accuracy: ...
  # rain_rate_accuracy: ...
  # wind_direction_accuracy: ...
  # wind_speed_accuracy: ...
