# config file for quality checks in mwr_raw2l1

# for quality_flag
check_missing_Tb: True
check_min_Tb: True
check_max_Tb: True
check_spectral_consistency: False
check_receiver_sanity: True
check_rain: True
check_sun: True  # check whether sun is in beam
check_Tb_offset: False

delta_azi_sun: 7  # minimum accepted absolute azimuth offset between instrument pointing and sun
delta_ele_sun: 7  # minimum accepted absolute elevation offset between instrument pointing and sun
Tb_threshold: [2.7, 330.0]   # Threshold for min and max Tb


# potential future extension for liquid_cloud_flag
